// Provider types
export type ProviderType = 
  | 'openai' 
  | 'claude' 
  | 'gemini' 
  | 'deepseek' 
  | 'groq' 
  | 'openrouter' 
  | 'qwen'
  | 'ollama';

export interface Provider {
  id: ProviderType;
  name: string;
  baseUrl: string;
  apiKeyPrefix: string;
  modelsEndpoint: string;
  chatEndpoint: string;
}

// Model types
export interface Model {
  id: string;
  name: string;
  provider: ProviderType;
  contextLength?: number;
  supportsVision?: boolean;
  supportsTools?: boolean;
}

// Trading tools
export type TradingTool =
  | 'fetch_prices'
  | 'fetch_news'
  | 'calculate_indicators'
  | 'calculate_rsi'
  | 'calculate_macd'
  | 'calculate_sma'
  | 'calculate_ema'
  | 'calculate_bollinger_bands'
  | 'calculate_atr'
  | 'calculate_stochastic';

export interface ToolCall {
  id: string;
  name: TradingTool;
  arguments: Record<string, unknown>;
  status: 'pending' | 'running' | 'completed' | 'error';
  result?: unknown;
  error?: string;
  timestamp: number;
}

// Analysis types
export type Recommendation = 'BUY' | 'SELL' | 'HOLD';

export interface TradingLevels {
  entry?: number;
  stopLoss?: number;
  takeProfit1?: number;
  takeProfit2?: number;
  takeProfit3?: number;
}

export interface AnalysisResult {
  id: string;
  recommendation: Recommendation;
  confidence: number; // 0-100 percentage
  reason: string;
  tradingLevels: TradingLevels;
  riskRewardRatio?: string;
  detectedSymbol?: string; // Symbol detected/generated by LLM
  detailedAnalysis: string;
  timestamp: number;
  symbol?: string;
  context?: string;
  images?: string[]; // base64 images
  model: string;
  provider: ProviderType;
  toolCalls: ToolCall[];
}

// Settings stored in localStorage
export interface ProviderSettings {
  apiKey: string;
  selectedModel: string;
}

export interface AppSettings {
  providers: Partial<Record<ProviderType, ProviderSettings>>;
  defaultProvider?: ProviderType;
}

// API request/response types
export interface AnalyzeRequest {
  images: string[]; // base64 encoded
  symbol?: string;
  context?: string;
  provider: ProviderType;
  model: string;
  apiKey: string;
}

export interface ToolResult {
  success: boolean;
  data?: unknown;
  error?: string;
}

// News types
export interface NewsItem {
  title: string;
  source: string;
  url?: string;
  publishedAt?: string;
  timestamp?: number;
  summary?: string;
  sentiment?: 'positive' | 'negative' | 'neutral';
}

// Price data types
export interface PriceData {
  symbol: string;
  price: number;
  change: number;
  changePercent: number;
  volume?: number;
  high24h?: number;
  low24h?: number;
  marketCap?: number;
  timestamp: number;
}

export interface OHLCV {
  timestamp: number;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
}

// Indicator types
export interface RSIResult {
  value: number;
  signal: 'overbought' | 'oversold' | 'neutral';
}

export interface MACDResult {
  macd: number;
  signal: number;
  histogram: number;
  trend: 'bullish' | 'bearish' | 'neutral';
}

export interface BollingerBandsResult {
  upper: number;
  middle: number;
  lower: number;
  bandwidth: number;
  position: 'above_upper' | 'below_lower' | 'within';
}

export interface StochasticResult {
  k: number;
  d: number;
  signal: 'overbought' | 'oversold' | 'neutral';
}
